/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZbBlogItemFlexible: typeof import('./src/components/common/zb-blogItem-flexible.vue')['default']
    ZbBlogItemRectangle: typeof import('./src/components/common/zb-blogItem-rectangle.vue')['default']
    ZbBlogItemRectangleMobile: typeof import('./src/components/mobile/zb-blogItem-rectangle-mobile.vue')['default']
    ZbCard: typeof import('./src/components/common/zb-card.vue')['default']
    ZbClassifyTool: typeof import('./src/components/common/zb-classify-tool.vue')['default']
    ZbCommentArea: typeof import('./src/components/common/zb-comment-area.vue')['default']
    ZbEmpty: typeof import('./src/components/common/zb-empty.vue')['default']
    ZbImageLazy: typeof import('./src/components/common/zb-image-lazy.vue')['default']
    ZbInfoItem: typeof import('./src/components/common/zb-infoItem.vue')['default']
    ZbItemInBook: typeof import('./src/components/common/zb-itemInBook.vue')['default']
    ZbLoading: typeof import('./src/components/common/zb-loading.vue')['default']
    ZbLoadMore: typeof import('./src/components/common/zb-loadMore.vue')['default']
    ZbProgress: typeof import('./src/components/common/zb-progress.vue')['default']
    ZbSearchResultBlogItemMobile: typeof import('./src/components/mobile/zb-searchResult-blogItem-mobile.vue')['default']
    ZbStickyBar: typeof import('./src/components/common/zb-sticky-bar.vue')['default']
    ZbSvgIcon: typeof import('./src/components/common/zb-svg-icon.vue')['default']
    ZbTheme: typeof import('./src/components/common/zb-theme.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
