/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZbBacktop: typeof import('./src/components/common/zb-backtop.vue')['default']
    ZbBlogItemFlexible: typeof import('./src/components/common/zb-blogItem-flexible.vue')['default']
    ZbBlogItemRectangle: typeof import('./src/components/common/zb-blogItem-rectangle.vue')['default']
    ZbBlogItemRectangleMobile: typeof import('./src/components/mobile/zb-blogItem-rectangle-mobile.vue')['default']
    ZbCard: typeof import('./src/components/common/zb-card.vue')['default']
    ZbClassifyTool: typeof import('./src/components/common/zb-classify-tool.vue')['default']
    ZbCommentArea: typeof import('./src/components/common/zb-comment-area.vue')['default']
    ZbEmojiInput: typeof import('./src/components/common/zb-emoji-input.vue')['default']
    ZbEmojiSelect: typeof import('./src/components/common/zb-emoji-select.vue')['default']
    ZbEmpty: typeof import('./src/components/common/zb-empty.vue')['default']
    ZbError: typeof import('./src/components/common/zb-error.vue')['default']
    ZbImage: typeof import('./src/components/common/zb-image.vue')['default']
    ZbInfoItem: typeof import('./src/components/common/zb-infoItem.vue')['default']
    ZbItemInBook: typeof import('./src/components/common/zb-itemInBook.vue')['default']
    ZbLoading: typeof import('./src/components/common/zb-loading.vue')['default']
    ZbLoadMore: typeof import('./src/components/common/zb-loadMore.vue')['default']
    ZbNotFound: typeof import('./src/components/common/zb-notFound.vue')['default']
    ZbProgress: typeof import('./src/components/common/zb-progress.vue')['default']
    ZbSearchResultBlogItemMobile: typeof import('./src/components/mobile/zb-searchResult-blogItem-mobile.vue')['default']
    ZbStickyBar: typeof import('./src/components/common/zb-sticky-bar.vue')['default']
    ZbSvgIcon: typeof import('./src/components/common/zb-svg-icon.vue')['default']
    ZbTag: typeof import('./src/components/common/zb-tag.vue')['default']
    ZbTheme: typeof import('./src/components/common/zb-theme.vue')['default']
    ZbTime: typeof import('./src/components/common/zb-time.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
